BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "resources" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"url"	TEXT NOT NULL,
	"hash"	TEXT NOT NULL,
	"user"	INTEGER NOT NULL,
	"size"	INTEGER
);
CREATE TABLE IF NOT EXISTS "comments" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"userId"	INTEGER NOT NULL,
	"votes"	TEXT NOT NULL,
	"date"	DATE NOT NULL,
	"headline"	TEXT NOT NULL,
	"content"	TEXT NOT NULL,
	"url"	TEXT
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"email"	TEXT,
	"trustLevel"	REAL
);
CREATE TABLE IF NOT EXISTS "sites" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"url"	TEXT,
	"comments"	TEXT
);
COMMIT;
