const ipAddress = "http://commentsense.de";

const langDe = {
    brandName: "CommentSense",
    home: "Home",
    signIn: "Anmelden",
    signInText: "Hier kommt noch ein Text hin",
    signInSuccessTitle: "Erfolgreich angemeldet",
    signInSuccessText: "Du hast dich erfolgreich angemeldet",
    signInErrTitle: "Fehler!",
    signInErrText: "Fehler beim anmelden",
    signUp: "Registieren",
    signUpText: "Hier kommt noch ein Text hin",
    signUpSuccessTitle: "Nutzer erstellt",
    signUpSuccessText: "Der Nutzer wurde erfolgreich erstellt",
    signUpErrTitle: "Fehler!",
    signUpErrText: "Der Nutzer konnte nicht erstellt werden",
    toWebsite: "zur Website wechseln",
    username: "Nickname",
    password: "Passwort",
    email: "E-mail",
    cancel: "Abbrechen",
    ok: "OK",
    saveChanges: "Änderungen speichern",
    account: "Account bearbeiten",
    github: "CommentSense auf Github",
    notFoundTitle: "Seite nicht gefunden!",
    notFoundText: "Die angefragte Seite konnte nicht gefunden werden.",
    loggedInAs: "Angemeldet als: ",
    logout: "Abmelden",
    addComment: "Kommentar schreiben",
    addCommentText: "Bitte fülle alle Felder aus",
    commentSend: "Kommentar senden",
    commentTitle: "Titel",
    commentText: "Kommentar",
    commentSuccessTitle: "Kommentar erfolgreich erstellt",
    commentSuccessText: "Hier kommt noch Text hin",
};


export { ipAddress, langDe };